- name: 'keyword_enhance'
  space: 'feature'
  quality: 'high'
  exinfo: 'tfidfs'

- name: 'random_word_dropout'
  space: 'feature'
  quality: 'low'

- name: 'tfidf_word_dropout'
  space: 'feature'
  quality: 'low'
  exinfo: 'dropout_prob'

- name: 'hidden_state_pooling'
  space: 'feature'
  quality: 'high'

- name: 'hidden_state_cnn'
  space: 'feature'
  quality: 'high'

- name: 'synonym_replacement'
  space: 'text'
  quality: 'high'

- name: 'random_deletion'
  space: 'text'
  quality: 'low'

- name: 'random_swap'
  space: 'text'
  quality: 'low'

- name: 'random_insertion'
  space: 'text'
  quality: 'high'

- name: 'loss_based_replacement'
  space: 'feature'
  quality: 'high'

- name: 'pred_based_replacement'
  space: 'feature'
  quality: 'high'

- name: 'pred_loss_replacement'
  space: 'feature'
  quality: 'high'

- name: 'online_random_replacement'
  space: 'feature'
  quality: 'high'