imdb:
  dataset: 'imdb'
  loading_way: 'huggingface'
  text_field: 'text'
  label_field: 'label'
  splits: {'train':25000, 'test': 25000, 'unsupervised': 50000}
  class_num: 2
rotten_tomatoes:
  dataset: 'rotten_tomatoes'
  loading_way: 'huggingface'
  text_field: 'text'
  label_field: 'label'
  splits: {'train': 8530, 'validation': 1066, 'test': 1066}
  class_num: 2
yelp-5:
  dataset: 'yelp_review_full'
  loading_way: 'huggingface'
  text_field: 'text'
  label_field: 'label'
  splits: {'train': 650000, 'test': 50000}
  class_num: 5
amazon-5:
  dataset: 'amazon_reviews_multi'
  subset: 'en'
  loading_way: 'huggingface'
  title_field: 'review_title'
  text_field: 'review_body'
  label_field: 'stars'
  splits: {'train': 200000, 'validation': 5000, 'test': 5000}
  class_num: 5
  label_dict:
    1: 0
    2: 1
    3: 2
    4: 3
    5: 4