# environment_params

environment: 'neimeng' # vpn, local, quanzhou, neimeng
---

# running_configs
default:
  dataset: 'sst-2' # sst-2, imdb, rotten_tomatoes, sentiment140, yelp-5, amazon-5
  model: 'distilbert'
  augmentations: []
  epochs: 3
  save_steps: 1000
  eval_steps: 100
  logging_steps: 100